<?php
/**
 * Created by PhpStorm.
 * User: mkkn
 * Date: 2018/05/09
 * Time: 19:32
 */

namespace Chatbox\ApiAuth\Tests\Request;

use Chatbox\ApiAuth\Tests\Response;
use Illuminate\Foundation\Testing\TestResponse;

trait LaravelTestTrait
{
    protected $headers = [];

    protected $response;

    protected function login($token)
    {
        $this->headers = [
            "Authorization" => "Bearer $token"
        ];
    }

    protected function logout()
    {
        $this->headers = [
        ];
    }

    public function tearDown()
    {
        $this->logout();
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Request::$runner = function (Request $request) {
            $this->refreshApplication();
            $server = $this->transformHeadersToServerVars($this->headers);
            /** @var TestResponse $response */
            $response = $this->call($request->method, $this->baseUrl.$request->path, $request->body, [], [], $server, null);
            $this->response = $response->baseResponse;
        };
    }

    protected function response():Response
    {
        return new Response($this->response);
    }
}
