<?php
/**
 * Created by PhpStorm.
 * User: mkkn
 * Date: 2018/05/09
 * Time: 19:32
 */

namespace Chatbox\ApiAuth\Tests\Request;

use Chatbox\ApiAuth\Tests\Response;

trait LumenTestTrait
{
    protected $headers = [];

    protected function login($token)
    {
        $this->headers = [
            "Authorization" => "Bearer $token"
        ];
    }

    protected function logout()
    {
        $this->headers = [
        ];
    }

    public function tearDown()
    {
        $this->logout();
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Request::$runner = function (Request $request) {
            $this->refreshApplication();
            $server = $this->transformHeadersToServerVars($this->headers);
            return $this->call($request->method, $request->path, $request->body, [], [], $server, null);
        };
    }

    protected function response():Response
    {
        return new Response($this->response);
    }
}
